--CRM
-- NOTE: The Silver tables don't need intitialization as dbt will automatically create them
-- CREATE TABLE IF NOT EXISTS silver.crm_cust_info(
--     cst_id INT,
--     cst_key VARCHAR(50),
--     cst_firstname VARCHAR(50),
--     cst_lastname VARCHAR(50),
--     cst_martial_status VARCHAR(10),
--     cst_gndr VARCHAR(10),
--     cst_create_date DATE,
--     dwh_create_date TIMESTAMP DEFAULT NOW()::TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS silver.crm_prd_info(
--     prd_id INT,
--     prd_key VARCHAR(50),
--     prd_nm VARCHAR(50),
--     prd_cost INT,
--     prd_line CHAR(1),
--     prd_start_dt DATE,
--     prd_end_dt DATE,
--     dwh_create_date TIMESTAMP DEFAULT NOW()::TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS silver.crm_sales_details(
--     sls_ord_num VARCHAR(8),
--     sls_prd_key VARCHAR(50),
--     sls_cust_id INT,
--     sls_order_dt VARCHAR(8),
--     sls_ship_dt VARCHAR(8),
--     sls_due_dt VARCHAR(8),
--     sls_sales INT,
--     sls_quantity INT,
--     sls_price INT,
--     dwh_create_date TIMESTAMP DEFAULT NOW()::TIMESTAMP
-- );
--ERP

-- CREATE TABLE IF NOT EXISTS silver.erp_cust_az12(
--     CID VARCHAR(13),
--     BDATE DATE,
--     GEN VARCHAR(10),
--     dwh_create_date TIMESTAMP DEFAULT NOW()::TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS silver.erp_loc_a101(
--     CID VARCHAR(11),
--     CNTRY VARCHAR(50),
--     dwh_create_date TIMESTAMP DEFAULT NOW()::TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS silver.erp_px_cat_g1v2(
--     ID VARCHAR(5),
--     CAT VARCHAR(50),
--     SUBCAT VARCHAR(50),
--     MAINTENANCE VARCHAR(3),
--     dwh_create_date TIMESTAMP DEFAULT NOW()::TIMESTAMP
-- );